#
# Module manifest for module 'event'
# Generated by: David Koenig
# Generated on: 2022-02-11
#

@{

    RootModule = 'buderus-km200.psm1'
    RequiredModules = @(@{ModuleName="Pode";ModuleVersion="2.6.0"})
    ModuleVersion = '0.0.1'
    CompatiblePSEditions = 'Core'
    GUID = 'c6c1c024-c6a7-481c-83b6-fa8d4bd47a2b'
    Author = 'David Koenig'
    CompanyName = 'Frickeldave'
    Copyright = '(c) David Koenig. All rights reserved.'
    Description = 'A module to access the buderus km200 web api gateway'
    FunctionsToExport = 'Initialize-KM200Api'
    CmdletsToExport = ''
    VariablesToExport = ''
    AliasesToExport = ''
    PrivateData = @{

        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
            # Prerelease = ''
            # RequireLicenseAcceptance = $false
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''
}